base:
  random_state: 42
  log_level: INFO

data_create:
  # Parametros para criar o dataset
  buffer_metros: 150
  delta_dias: 2
  latitude: -30.012175
  longitude: -51.215679
  nome_eta: "MOINHOS DE VENTO"
  municipio: "PORTO ALEGRE"
  manancial: "GUAIBA"
  url: "https://sage.saude.gov.br/dados/sisagua/controle_mensal_demais_parametros.zip"

data_load:
  s2a_df: "data/raw/gee.csv"
  labels_download: "data/raw/controle_mensal_demais_parametros.zip"
  labels_df: "data/raw/vigi.csv"
  labeled_df: "data/raw/labeled_data.csv"

gee_clean:
  train_new_clf: True
  imgs_com_nuvens: [
    "2019-06-17",
    "2020-08-07",
    "2020-12-28",
    "2021-01-22",
    "2022-01-19",
    ]
  kmeans:
    n_clusters: 6
    clean_cluster: [5]
  classifier:
    clf_name: logit
    clf_path: "models/cloud_clf.joblib"
    clf_performance: "reports/cloud_clf.json"
  clean_data_path: "data/processed/gee_clouds.csv"

featurize:
  target_column: "Resultado"
  selected_clean_columns: [
        'date',
        'NDVI_median',
        'NDCI_median',
        'B1_median',
        'B2_median',
        'B3_median',
        'B4_median',
        'B5_median',
        'B6_median',
        'B7_median',
        'B8_median',
        'B8A_median',
        'B9_median',
        'B11_median',
        'B12_median'
        ]
  selected_features: [
    "B1_median B5B3_B2" ,
    "B3_B2 B5B3_B2" ,
    "B3_B4" ,
    "B3_B4 B5B3_B2" ,
    "B4_median B3_B2" ,
    "B4_median B5B3_B2" ,
    "B5B3_B2" ,
    "B5B3_B2^2" ,
    "B5_B4^2" ,
    "B5_median B5B3_B2" ,
    "B6_median^2" ,
    "B8A_median B5B3_B2" ,
    "B9_median B3_B4" ,
    "B9_median B5B3_B2" ,
    "B11_median^2",
    "delta_days",
    "NDCI_median B5_B4" ,
    "NDVI_median B5_B2"]
  poly_degree: 2
  ft_data_path: "data/processed/df_fts.csv"

data_split:
  trainset_path: "data/processed/train.csv"
  testset_path: "data/processed/test.csv"
  years_split_test: 1

mlflow_config:
  experiment_name: "change_days"

train:
  estimator_name: ridge
  estimators:
    ridge:
      params:
        alpha: 0.005
    xgboost:
      params:
        n_estimators: 1000
        learning_rate: 0.5
        max_depth: 16
        subsample: 0.8
        colsample_bytree: 0.9
        colsample_bylevel: 0.4
        scale_pos_weight: 85
    random_forest:
      params:
        max_features: "sqrt"
        min_samples_leaf: 1
        n_estimators: 615
        criterion: "absolute_error"
  model_path: "models/model.joblib"
  full_model_path: "models/full_model.joblib"

evaluate:
  metrics_file: "reports/metrics.json"
  metrics_data: "reports/metrics.csv"
  predicted_vs_fitted_plot: "reports/predicted_vs_fitted_plot.png"
  final_predictions_file: "data/predictions/predicted.csv"
